### ISSUE TITLE
Graft Release v1.0.1 Build Failed OSX

### ISSUE THREAD

**Issue by s4m0k** [graft-project/GraftNetwork#103]
Hi Guys, I'm having trouble building Graft Release v1.0.1.

Build Environment:
- Operating System: OSX Version 10.13.3 (MacOS Sierra)
- All required build dependencies installed using brew
  - boost 1.66.0
  - boost-python 1.66.0_1
  - cmake 3.10.3
  - gcc 7.3.0_1
  - openssl 1.0.2o_1 1.0.2n
  - pkg-config 0.29.2
  - unbound 1.7.0

The error that i get is
`Undefined symbols for architecture x86_64:`
 `"supernode::TxPool::m_rpc_timeout", referenced from:`

Attached is an image with the actual build error. 
However when i tried building source from github master, i dont get any errors at all and  all binaries are built successfully. I only get the compile/build error as mentioned above from the release source v1.0.1.  Hope you can lead me to the right directions. 

Thank you.

<img width="1303" alt="graft-1 0 1-build-error" src="https://user-images.githubusercontent.com/3829536/38503939-fe22a780-3c45-11e8-8046-93ef3f146f02.png">

**Comment by mbg033** [comment]
Yes, that was a bug, it was fixed in master. You can either use master or cherry-pick commit 58d93394422feb90eb690393d4c0e0fe1985016c

**Comment by s4m0k** [comment]
thank you.  I do cherry picking so that my node still looks like an official release.
