### ISSUE TITLE
Block 65110 is going to be miner later than expected

### ISSUE THREAD

**Issue by imperdin** [graft-project/GraftNetwork#107]
At the current mining speed to hit the April 14th target date, miner would need to mine the 1535 blocks needed to fork at +- 110 MH/s however, at the current difficulty the "real" MH/s used to mine graft is closer to 3-4 MH/s so miner are going to mine at about 1 Block, 1 Hour until +- 520 blocks are mined and the difficulty will begin to re-adjust .
Please change the target block to 63640 in order to upgrade at around April 14th

At current mining speed, block 65110 is more likely to be mined April 30th or later. It could take more than 16 days at current mining speed just to mine 720 blocks

**Comment by saiaman** [comment]
Looks like the network is saturated .... no block since 3 hours .... at this speed the fork will occur un June !

**Comment by imperdin** [comment]
Monero difficulty adjustment algorithm SMA, needs about 520 blocks to better adjust the difficulty, SMA also ignore the 60 slowest block and 60 fastest blocks, so the next 2 days at the current difficulty are bond to the slowest blocks as Graft is only mined at 3% of the difficulty MH/s so there are only going to be around 3% of the average mined blocks per day at the current speeds. So two days just to reach the 60 ignored block point obstacle
