### ISSUE TITLE
Idea for preventing delayed blocks

### ISSUE THREAD

**Issue by zawy12** [graft-project/GraftNetwork#117]
Although there has not been noticeable delays in coins using LWMA with FTL=500 (on rare occasions there has been a single 15xT delay), Graft posted an idea about trying to prevent delayed blocks.  I described in the closed difficulty issue why I don't think it would help.  But here's a modification of Andrew Stone's idea. His idea is a linear lowering of the difficulty as more and more time passes beyond a certain point.  Miners assign the timestamps, so they could assign a forward time up to a limit to make the difficulty easier. The motivation against these bad timestamps is that if someone assigns a smaller time and wins the higher difficulty, they have created a chain with more work, so the cheater's block could get reverted.

My idea is to make it discrete instead of a linear drop in difficulty.    If node time is passed to the difficulty algorithm, the rule would be "If a block's timestamp is 10xT since previous block, then difficulty will be 1/3 the calculated difficulty, if the timestamp is not more than +/- 3xT away from node time."  The  +/- 350 is intentionally a little less than FTL.  Then at 20xT a 1/9 difficulty will be accepted.

**Comment by sebseb7** [comment]
Do same simulations with realistic data.
