### ISSUE TITLE
graftnoded CPU 97.9 %

### ISSUE THREAD

**Issue by TheBudda** [graft-project/GraftNetwork#134]
graftnoded is synced and been running ok. When I start graftnoned its fine then it creeps up on CPU power. Now it's using 97% of CPU. Can you please help with this issue?

**Comment by jagerman** [comment]
I have seen this on my pool, particularly when there are old transactions in the mempool that aren't being included for some reason (I haven't tracked down exactly what the "some reason" is, but the transactions never get included in a block).  The pool polls the node for the block template repeatedly (to look for a new block template), and when a handful of these transactions are present each poll seems to take a considerably amount of CPU time, while in normal situations the CPU time on each poll is minimal.

A `flush_txpool` on the node will work around the problem when it occurs.

**Comment by TheBudda** [comment]
Hi, jagerman, 
Thanks for your reply. I have tried to execute the command and I get this: [wallet GBHnvw]: fluh_txpool
unknown command: fluh_txpool

There is no command flush_txpool in graft-wallet-cli. When I type help in graft-wallet-cli, flush_txpool is not even in the help list of commands :/

**Comment by TheBudda** [comment]
Yes, I read this about an hour ago. Nice one due for the info, I appreciate your support with my issue
