### ISSUE TITLE
MacOS POS wallet v2.0.2 cannot remove or edit products once created

### ISSUE THREAD

**Issue by yidakee** [graft-project/GraftNetwork#142]
After the creation of products, this version of POS wallet does not seem to allow to delete or edit items. OSX 10.13.6

**Comment by EDDragonWolf** [comment]
press on some item and move mouse left. It should help.

**Comment by yidakee** [comment]
Ah, good one. Mobile behaviour on desktop, didn't even think of trying that. I suggest adding a visual cue, like 3 dots or something

**Comment by EDDragonWolf** [comment]
Yeah. Currently, we thinking about redesign both the mobile and desktop version of our clients.

**Comment by EDDragonWolf** [comment]
Since there are no other issues related to it, I close this issue.
