### ISSUE TITLE
Fix the wording and function of donate in CLI

### ISSUE THREAD

**Issue by mechanator** [graft-project/GraftNetwork#169]
Changes the default wallet address for donations to developers within the wallet CLI interface. Reports to the user that the donation address is an open alias address called donate@graft.network.
The main devs need to make a new open alias and administer the donations.
Currently the original code reports the donate as going to the Monero project and not the Graft Network project.
Also the original donation address is a Monero XMR address and not a Graft Network address.
When attempting to donate, and error is reported, "Error: failed to parse address".
So this defect has two error levels. Functional, since it doesn't work, and cosmetic since it tells the user information about using Monero and not Graft.
A suggestion would be to use the donations collected as a bug bounty reward system for contributors of code outside of employed Graft Inc.  developers as deemed appropriate.  Maybe a vote for dispensation by peer review of bug submitter to elect who and how much of the donation goes to and how frequent this happens. This would be a fair, democratic, and equitable way to handle donations.
Another alternative is to remove the donate feature completely from the CLI wallet.
--Proposed changes in simplewallet.cpp are:
bool simple_wallet::donate(const std::vector<std::string> &args_)
{
  std::vector<std::string> local_args = args_;
  if(local_args.empty() || local_args.size() > 3)
  {
     fail_msg_writer() << tr("wrong number of arguments");
     return true;
  }
  std::string ring_size_str;
  // Hardcode Graft's donation address set to something other than the Monero address until the dev edit this to a new graft address or an open alias address.
  const std::string address_str = "donate@graft.network";

and

    local_args.push_back(payment_id_str);
  message_writer() << tr("Donating ") << amount_str << " Graft to The Graft Network Project (donate@graft.network).";

**Comment by crazy-logic** [comment]
+1 for these - The simple_wallet.ccp is full of Monero references.

**Comment by avastar** [comment]
this has been completed #282 and can be closed @mbg033
