### ISSUE TITLE
Graft under 51% attack

### ISSUE THREAD

**Issue by zawy12** [graft-project/GraftNetwork#208]
I've been informed a 51% attack on graft began 45 minutes ago.  Current blocks may suffer a rollback to 261669.   So 261670 up until now could become invalid.   

**edit:**  An hour after it began, attacker's chain ended at 261703 while the one it's replacing is at 261696.  So it looks like 27-blocks will be orphaned.

**Comment by bobbieltd** [comment]
Great work ! Thanks alot for keep me (and others) update.

**Comment by zawy12** [comment]
Correction, seems like there was a counter attack.  Maybe only 10, mostly from hashvault, will be orphaned.  They were unlucky to have high luck at the wrong time.

**Comment by MentalNomad** [comment]
For future reference:

![image](https://user-images.githubusercontent.com/34785888/51131193-ffa96600-17fc-11e9-9112-24d43c792cf0.png)

**Comment by Swericor** [comment]
The nominal hashrate seems to be 50% off in that graph.

**Comment by MentalNomad** [comment]
Graft Nethash is roughly 10 MH/s and appears to trend around that level.

The graph is not showing Graft hashrate, it is showing NiceHash's available power to rent.

You'll note that, during the attack and counterattack period, "paying" went up - indicating people were bidding on CryptoNightV8 hashpower - which drove up the actual hashrate available. In other words, the bidding attracted more miners (through automation and manual choices), increasing the hashrate in the NiceHash CryptoNighV8 market.

**Comment by Swericor** [comment]
Yes, you're right. Sorry about that, I didn't read properly.

**Comment by zawy12** [comment]
Attacker returned about 15 hours ago, in case anyone noticed.

**Comment by EDDragonWolf** [comment]
Since this issue strongly related to PoW change, it will be closed after merging Reverse Waltz tweak and planning new HF. If you have other suggestions, please, inform me.
