### ISSUE TITLE
Zelerius network is using this iterations

### ISSUE THREAD

**Issue by nilhcraiv** [graft-project/GraftNetwork#224]
Please consider this number of iterations is used by **Zelerius** network as cryptonight_zlx https://github.com/fireice-uk/xmr-stak/pull/2196 and https://github.com/xmrig/xmrig/issues/923

Have you thought about including this change in the next hard fork or it was just an idea? please explain the situation.

https://github.com/graft-project/GraftNetwork/blob/57e9078c79e543f4268d6cef23443aa8a11499e6/src/crypto/slow-hash.c#L768

**Comment by Patrickdurbin** [comment]
They need to answer you! This is ridiculous! did you ever fork to this algo?
