### ISSUE TITLE
XXX Be careful when merging back to master, in master "halving" version is 10

### ISSUE THREAD

**Issue by jagerman** [graft-project/GraftNetwork#267]
https://github.com/graft-project/GraftNetwork/blob/a3985793caad75cb61369b8f0dd5ca81316f6b41/src/cryptonote_basic/cryptonote_basic_impl.cpp#L117-L120

https://github.com/graft-project/GraftNetwork/blob/a3985793caad75cb61369b8f0dd5ca81316f6b41/src/cryptonote_basic/cryptonote_basic_impl.cpp#L147-L150

**Comment by ku4eto** [comment]
Gotta say, leaving a comment like that is a really bad practice...
