### ISSUE TITLE
1.7.5 deadlocks

### ISSUE THREAD

**Issue by jagerman** [graft-project/GraftNetwork#281]
Since the upgrade to 1.7.5 I've noticed deadlocks occurring which completely lock up the graftnoded.  These did not occur in 1.7.4, and have not occurred again since I downgraded to 1.7.4.

The issue is almost certainly here:

https://github.com/graft-project/GraftNetwork/blob/91511ea735ea49db5a422617900ae4057e23c84f/src/cryptonote_core/stake_transaction_processor.cpp#L286-L288

where the 1.7.5 code was changed to establish two independent locks non-atomically (`m_storage_lock`, plus a lock on the blockchain via the call to `get_current_blockchain_height()`), which is a basic recipe for a deadlock.

**Comment by Fez29** [comment]
I have also experienced lockups since 1.7.5, where graftnoded does not respond to status requests made to it and stop syncing as well. 

Previous to this version I have not experienced this issue.

**Comment by ku4eto** [comment]
Same. The 18981 port becomes locked for no reason. Even thought `netstat -l` says its listening on `localhost:18981`, if you try to telnet to it, it will fail.

**Comment by mbg033** [comment]
we're looking into it

**Comment by jagerman** [comment]
This seems to fix it - no one on the community branch since upgrading to that version has reported a lockup yet:

https://github.com/graft-community/GraftNetwork/commit/50bd42c6ef95acd38e5133b8b925c2d77b356c3d

**Comment by Patrickdurbin** [comment]
![image](https://user-images.githubusercontent.com/36722911/56998431-e2609380-6b70-11e9-9b12-7b7e9a4a4f9b.png)

**Comment by Patrickdurbin** [comment]
![image](https://user-images.githubusercontent.com/36722911/56998460-02905280-6b71-11e9-936f-40bf53eb28ce.png)

**Comment by Patrickdurbin** [comment]
![image](https://user-images.githubusercontent.com/36722911/56998489-176ce600-6b71-11e9-8727-2d72b41bf622.png)

**Comment by Patrickdurbin** [comment]
fuck looking into merge the patch

**Comment by Patrickdurbin** [comment]
This is the only exchange open now... https://www.myqbtc.com/trade?symbol=GRFT_CNYT

**Comment by mbg033** [comment]
Thanks @jagerman 
patch released as [1.7.6](https://github.com/graft-project/GraftNetwork/releases/tag/v1.7.6)
