### ISSUE TITLE
[JSON RPC] `close_wallet` - method not found

### ISSUE THREAD

**Issue by TomoHavvk** [graft-project/GraftNetwork#283]
Please add `close_wallet` method. - https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#close_wallet

**Request:** `{"jsonrpc":"2.0","id":"0","method":"close_wallet"}`
**Response:**
Actual: `{ "error": { "code": -32601, "message": "Method not found" }, "id": "", "jsonrpc": "2.0"}`
Expect: `{ "id": "0", "jsonrpc": "2.0", "result": { } }`

**Comment by mbg033** [comment]
@TomoHavvk it will be available in next release (merge with monero v13)

**Comment by TomoHavvk** [comment]
@mbg033 Understood, thanks.
