### ISSUE TITLE
graftnoded reflecting: "Hash rate: 0.000 MH/s" and "Network difficulty: 0" when syncing from scratch

### ISSUE THREAD

**Issue by Fez29** [graft-project/GraftNetwork#284]
Hi

When syncing graftnoded from blockheight 0, I get the below mentioned results everytime when I attempt to do this. I have attempted this multiple times and the symptom has been raised numerous times on the Graft Telegram groups "Graft Blockchain" and "Graft Supernode Group". After further analysis by @jagerman it appears the issue starts at blockheight 176000, the fix to avoid this is to download the raw copy of the blockchain and the then start graftnoded and then this does not occur.

Network difficulty: 0 | Hash rate: 0.000 MH/s.

Now I have managed to get results of this being attempted (to sync from 0) and attached the Graft Block explorer to that same graftnoded. The results are seen below.

![image](https://user-images.githubusercontent.com/41666396/56970299-2353aa80-6b67-11e9-88dd-9ea33b42651d.png)

I have taken the liberty of looking through transactions and comparing them to the graft.observer block explorer (Which shows Nethash and Difficulty correctly) and found that the Transactions are all aligned and the graftnoded with "Network difficulty: 0 | Hash rate: 0.000 MH/s." . See below: For block 337963

Node showing 0 Nethash

![image](https://user-images.githubusercontent.com/41666396/56970482-804f6080-6b67-11e9-9eea-8a8b16d45550.png)

graft.observer

![image](https://user-images.githubusercontent.com/41666396/56970578-b5f44980-6b67-11e9-8257-8caf61542b09.png)

Block 337974

Node showing 0 Nethash

![image](https://user-images.githubusercontent.com/41666396/56970645-db815300-6b67-11e9-8e19-7138c004c720.png)

graft.observer

![image](https://user-images.githubusercontent.com/41666396/56970704-0370b680-6b68-11e9-9459-d67f6ce7c966.png)

Screenshot of Block height 176000

Graftnoded that reflects 0 Nethash:

![image](https://user-images.githubusercontent.com/41666396/56988125-94a75380-6b8f-11e9-868c-733e7d79148b.png)

**Comment by Fez29** [comment]
variances in difficulty can be seen starting from block 176000

graft.observer:

height | age [d:h:m:s] | difficulty | size [kB]

176011 | 225:01:05:17 | 1519721799 | 13.63
176010 | 225:01:06:24 | 1549693852 | 42.98
176009 | 225:01:09:49 | 1510037241 | 0.10
176008 | 225:01:09:55 | 1480473912 | 13.63
176007 | 225:01:10:25 | 1469235608 | 13.64 |  
176006 | 225:01:11:48 | 1526750969 | 216.32
176005 | 225:01:16:40 | 1490947349 | 268.68
176004 | 225:01:16:56 | 1572820490 | 293.42
176003 | 225:01:22:51 | 1858066963 | 146.01
176002 | 225:01:36:48 | 1910706141 | 218.55
176001 | 225:01:40:28 | 2178202431 | 195.06
176000 | 225:01:48:37 | 2170678407 |227.68
175999 | 225:01:50:21 | 1994626391 |199.73
175998 | 225:01:50:31 | 1965534475 | 213.77

graftnoded showing 0 Nethash:

height | age [d:h:m:s] | difficulty | size [kB]

176011 | 225:01:16:25 | 1509891430 | 13.31
176010 | 225:01:17:32 | 1539833831 | 41.97
176009 | 225:01:20:57 | 1426261831 | 0.10
176008 | 225:01:21:03 | 1399406255 | 13.31
176007 | 225:01:21:33 | 1389815510 | 13.32
176006 | 225:01:20:04 | 1445305626 | 211.25
176005 | 225:01:24:10 | 1412427865 | 262.38
176004 | 225:01:24:26 | 1491094923 | 286.55
176003 | 225:01:23:53 | 1763034223 | 142.59
176002 | 225:01:35:46 | 1912609451 | 223.79
176001 | 225:01:39:26 | 2180330349 | 199.74
176000 | 225:02:03:56 | 2061748932 | 222.34
175999 | 225:02:05:40 | 1994626391 | 195.05
175998 | 225:02:05:50 | 1965534475 | 208.76

**Comment by Fez29** [comment]
Also notice the timestamp on block 16003 is a full minute out when compared to graft observer

**Comment by sc0ch** [comment]
same shit! can't sync anymore. fix it.

**Comment by ku4eto** [comment]
> 
> 
> same shit! can't sync anymore. fix it.
> ![image](https://user-images.githubusercontent.com/5249710/57012277-4be2af80-6c0e-11e9-9953-3d4a9a0641d0.png)

Thats the stupid issue with the alternative block chain present.

You gotta pop blocks, like 50k of them to sync properly. Also, use the 1.7.x wallet and graftnoded.

**Comment by Fez29** [comment]
@ku4eto from what I have seen, it is the correct chain but the difficulty is incorrect and this starts from blockheight 176000, which is a fork height, to V10. I have attempted pop-blocks with many different numbers of blocks and never been successful.

**Comment by ku4eto** [comment]
> 
> 
> @ku4eto from what I have seen, it is the correct chain but the difficulty is incorrect and this starts from blockheight 176000, which is a fork height, to V10. I have attempted pop-blocks with many different numbers of blocks and never been successful.
> 
> I shall however wait on my latest sync to get 100% synced and attempt with 50K anyways.

It would be faster to use that LMDB on Amazon...

**Comment by jagerman** [comment]
> It would be faster to use that LMDB on Amazon...

This isn't about faster, this is about being able to sync the chain from scratch correctly: it's a serious bug that this cannot be done.

There's a fix here that Fez confirmed fixed the problem:

https://github.com/graft-community/GraftNetwork/commit/b68bcd1b3b9e31bfee1a9e5af91511ee4ba945e2

**Comment by Fez29** [comment]
This Issue has now been fixed on Graft-Community with Commit ID: b68bcd1b3b9e31bfee1a9e5af91511ee4ba945e2

, instead of gradually decreasing down to 0 H/s  after blockheight 176000 , the nethash is now maintaining the Nethash and Difficulty, 

The above commit was included in v1.7.6 graft community deb packages. 

graft@buster-block:~$ graftnoded --version
Graft 'Delta Velorum' (v1.7.6-gc1-1-graft.community)
graft@buster-block:~$ graftnoded status
Height: 185065/339680 (54.5%) on mainnet, not mining, net hash 9.24 MH/s, net diff 1108898329, v10, up to date, 8(out)+2(in) connections, uptime 0d 2h 3m 54s
graft@buster-block:~$ graftnoded status
Height: 185765/339680 (54.7%) on mainnet, not mining, net hash 9.20 MH/s, net diff 1104587047, v10, up to date, 5(out)+2(in) connections, uptime 0d 2h 6m 14s
graft@buster-block:~$ graftnoded status
Height: 186865/339683 (55.0%) on mainnet, not mining, net hash 9.79 MH/s, net diff 1174936459, v10, up to date, 8(out)+0(in) connections, uptime 0d 2h 11m 21s
graft@buster-block:~$ graftnoded status
Height: 188865/339686 (55.6%) on mainnet, not mining, net hash 8.14 MH/s, net diff 977397490, v10, up to date, 7(out)+3(in) connections, uptime 0d 2h 18m 58s

Successful full sync:

graftnoded status
Height: 340095/340095 (100.0%) on mainnet, not mining, net hash 10.23 MH/s, net diff 1228143030, v13, up to date, 8(out)+4(in) connections, uptime 0d 15h 48m 9s

Thanks @jagerman
