### ISSUE TITLE
Compile error on Ubuntu 16.04

### ISSUE THREAD

**Issue by BKdilse** [graft-project/GraftNetwork#306]
Please advise on the following (tried normal release and static one):

`[ 43%] Building CXX object src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_core.cpp.o
/usr/local/src/GraftNetwork.NEW/src/cryptonote_core/cryptonote_core.cpp: In member function ‘size_t cryptonote::core::get_block_sync_size(uint64_t) const’:
/usr/local/src/GraftNetwork.NEW/src/cryptonote_core/cryptonote_core.cpp:1068:16: error: comparison of unsigned expression >= 0 is always true [-Werror=type-limits]
     if (height >= quick_height)
                ^
cc1plus: all warnings being treated as errors
src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/build.make:75: recipe for target 'src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_core.cpp.o' failed
make[3]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_core.cpp.o] Error 1
make[3]: Leaving directory '/usr/local/src/GraftNetwork.NEW/build/Linux/master/release'
CMakeFiles/Makefile2:1392: recipe for target 'src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/all' failed
make[2]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/all] Error 2
make[2]: Leaving directory '/usr/local/src/GraftNetwork.NEW/build/Linux/master/release'
Makefile:140: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/local/src/GraftNetwork.NEW/build/Linux/master/release'
Makefile:107: recipe for target 'release-static' failed
make: *** [release-static] Error 2
`

**Comment by BKdilse** [comment]
Advice recevied from Beni on Telegram, to run `make release CXXFLAGS="-Wno-type-limits"`  this has worked for me.

I'll leave this open, in case devs need to do anything about this.

**Comment by BeniSandu** [comment]
This is caused by this commit: https://github.com/graft-project/GraftNetwork/commit/c926750837cc7f669540dde486a428c99b527a85 , which makes quick_height always be 0.
