### ISSUE TITLE
Updated steps are required for building the Windows Wallets for v1.8.1

### ISSUE THREAD

**Issue by BKdilse** [graft-project/GraftNetwork#307]
Current steps fail due to various issues, Boost version, OpenSSL etc.

Is there a working solution to this?

**Comment by mbg033** [comment]
@BKdilse Windows build fix coming soon

**Comment by BKdilse** [comment]
loads of `icu` related errors after it compile graft-wallet-rpc, and starts to compile supernode, then fails.
