### ISSUE TITLE
Widows compile is still failing for 1.8.2

### ISSUE THREAD

**Issue by BKdilse** [graft-project/GraftNetwork#317]
Previous issue #307 but cannot re-open it.  This still fails for me.

Appreciate the updated steps and code, but now failing further down...

Not it compiles graft-wallet-rpc, and starts to compile supernode, then fails with a whole load of icu related errors. So still not right.

Was this tested?  I've tested this using a clean install of the build environment.

**Comment by ku4eto** [comment]
Still no response and fix for this?

Even with `libboost 1.69`, as in the README.md, the build for `supernode.exe` and `graft-wallet-cli.exe` still fails, in the way described above. Tons of `undefined` errors, no red errors though. Thats literally the linking of the last 2 binaries. 

Do you even do QA on those releases?!

**Comment by BKdilse** [comment]
will re-open when trying to compile newer version.
