### ISSUE TITLE
Wallet hangs trying to sync after block 602486

### ISSUE THREAD

**Issue by minerrocks** [graft-project/GraftNetwork#359]
Hello, we have a graft pool: graft.miner.rocks
And today we faced an issue - wallet cannot sync with daemon anymore.
We have tried to create new wallet, with new mnemonic seed - the issue remains.
When wallet tried to sync with daemon - daemon eats 100% CPU - and wallet hangs, until daemon stopped.

**Comment by Swericor** [comment]
Which version of the daemon are you running?

**Comment by minerrocks** [comment]
Latest release 1.9.2
https://github.com/graft-project/GraftNetwork/releases/latest

Looks like rpc wallet works, as payments are processed.
And daemon even when using 100% CPU after wallet makes request - still in sync with network.
OS: Ubuntu 18.04

**Comment by mbg033** [comment]
@minerrocks 
if you still can reproduce the issue, can you please start the wallet with "--log-level 2", make sure it stuck and email  me the log?

**Comment by minerrocks** [comment]
Looks like now it works ok, does not stuck, even for wallet created at height when issue was noticed.
