### ISSUE TITLE
Fatal Error during make build

### ISSUE THREAD

**Issue by Tachypsychia** [graft-project/GraftNetwork#40]
Following the guide explicitly copy and pasting all commands.
Here is theterminal dump:

[ 44%] Building CXX object src/supernode/CMakeFiles/obj_supernode.dir/PosSaleObject.cpp.o
/home/tachy/GraftNetwork/src/supernode/PosSaleObject.cpp:34:23**: fatal error: uuid/uuid.h: No such file or directory**
compilation terminated.
src/supernode/CMakeFiles/obj_supernode.dir/build.make:374: recipe for target 'src/supernode/CMakeFiles/obj_supernode.dir/PosSaleObject.cpp.o' failed
make[3]: *** [src/supernode/CMakeFiles/obj_supernode.dir/PosSaleObject.cpp.o] Error 1
make[3]: Leaving directory '/home/tachy/GraftNetwork/build/release'
CMakeFiles/Makefile2:1413: recipe for target 'src/supernode/CMakeFiles/obj_supernode.dir/all' failed
make[2]: *** [src/supernode/CMakeFiles/obj_supernode.dir/all] Error 2
make[2]: Leaving directory '/home/tachy/GraftNetwork/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/tachy/GraftNetwork/build/release'
Makefile:62: recipe for target 'release-all' failed
make: *** [release-all] Error 2

**Comment by EDDragonWolf** [comment]
Thanks, fixed. Please, check.

**Comment by Tachypsychia** [comment]
All good!
