### ISSUE TITLE
Blockchain Explorer unable to Build

### ISSUE THREAD

**Issue by Tachypsychia** [graft-project/GraftNetwork#67]
I cant create an issue in blockchain explorer so Im inputting the log file here

[  5%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
In file included from /home/tachy/graft-blockchain-explorer/src/MicroCore.h:10:0,
                 from /home/tachy/graft-blockchain-explorer/src/MicroCore.cpp:5:
/home/tachy/graft-blockchain-explorer/src/monero_headers.h:19:37: fatal error: release/version/version.h: No such file or directory
compilation terminated.
src/CMakeFiles/myxrm.dir/build.make:62: recipe for target 'src/CMakeFiles/myxrm.dir/MicroCore.cpp.o' failed
make[2]: *** [src/CMakeFiles/myxrm.dir/MicroCore.cpp.o] Error 1
CMakeFiles/Makefile2:254: recipe for target 'src/CMakeFiles/myxrm.dir/all' failed
make[1]: *** [src/CMakeFiles/myxrm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mirei83** [comment]
follow the whole howto, including the "make" of the normal GraftNetwork build. Its needed.

**Comment by AYeropudov** [comment]
same issue. All steps from readme well done.

**Comment by mbg033** [comment]
Fixed in https://github.com/graft-project/graft-blockchain-explorer/pull/2
Enabled issues for [graft-blockchain-explorer](https://github.com/graft-project/graft-blockchain-explorer/) project
