### ISSUE TITLE
(FreeBSD) unable to build 

### ISSUE THREAD

**Issue by santosha2003** [graft-project/GraftNetwork#79]
[ 62%] Linking CXX executable ../../bin/graft-supernode
..
supernode/TxPool.cpp:(.text+0x435): undefined reference to `supernode::TxPool::m_rpc_timeout

**Comment by kaybie3** [comment]
Same for me:

FreeBSD 10.4-RELEASE
autoconf-2.69_1                    =
autoconf-wrapper-20131203          =
automake-1.15.1                    =
automake-wrapper-20131203          =
bind910-9.10.4P6                   <
binutils-2.30_2,1                  =
bison-3.0.4,1                      =
boost-jam-1.66.0                   =
boost-libs-1.66.0                  =
ca_root_nss-3.34.1                 <
cmake-3.10.2                       =
curl-7.57.0                        <
cvsps-2.1_2                        =
dialog4ports-0.1.6                 =
expat-2.2.5                        =
gcc-6                              =
gcc-ecj-4.5                        =
gcc6-6.4.0_3                       =
gettext-runtime-0.19.8.1_1         =
gettext-tools-0.19.8.1             =
git-2.15.1                         <
gmake-4.2.1_1                      <
gmp-6.1.2                          =
help2man-1.47.5                    <
icu-60.2_2,1                       =
idnkit-1.0_6                       <
indexinfo-0.3.1                    =
json-c-0.12.1                      <
jsoncpp-1.8.1_2                    <
ldns-1.7.0_1                       =
libarchive-3.3.2,1                 =
libedit-3.1.20150325_2,1           <
libevent-2.1.8_1                   =
libffi-3.2.1_2                     =
liblz4-1.8.0,1                     <
libmicrohttpd-0.9.52               <
libnghttp2-1.29.0                  <
libtool-2.4.6                      =
libunwind-20170615                 =
libuv-1.18.0                       <
libxml2-2.9.4                      <
lzma-16.04                         =
lzo2-2.10_1                        =
m4-1.4.18,1                        =
miniupnpc-2.0.20170509             =
mpc-1.0.3                          =
mpfr-3.1.6                         =
p5-Authen-SASL-2.16_1              =
p5-Digest-HMAC-1.03_1              =
p5-Error-0.17025                   =
p5-GSSAPI-0.28_1                   =
p5-Locale-gettext-1.07             =
pcre-8.40_1                        =
perl5-5.24.3                       =
pkg-1.10.3_1                       <
pkgconf-1.3.10,1                   <
portmaster-3.17.10                 <
py27-Babel-2.5.1                   =
py27-Jinja2-2.10                   =
py27-MarkupSafe-1.0                =
py27-alabaster-0.7.6               =
py27-docutils-0.14_1               =
py27-imagesize-0.7.1               =
py27-meld3-0.6.8_2                 =
py27-pygments-2.2.0                =
py27-pystemmer-1.3.0_1             =
py27-pytz-2017.3,1                 <
py27-setuptools-36.5.0             <
py27-six-1.11.0                    =
py27-snowballstemmer-1.2.0_1       =
py27-sphinx-1.4.8_2,1              <
py27-sphinx_rtd_theme-0.2.4        =
py27-supervisor-3.3.3,1            =
python2-2_3                        =
python27-2.7.14_1                  =
readline-7.0.3_1                   =
rhash-1.3.5                        =
scons-2.5.1_1                      <
unbound-1.6.8_2                    =
zip-3.0_1                          =
zsh-5.3.1_1                        <
